baseURL = "https://nekotheshadow.github.io/"
languageCode = "ja"
title = "neko the shadow"
theme = "hyde-hyde"

[[menu.main]]
  name = "home"
  url = "/"

[[menu.main]]
  name = "infomation"
  url = "/infomation"

[params]
  themeColor = "theme-base-09"
  copyright = "neko the shadow"
  description = "personal stuff"
  dateformat = "2006-01-02"

